# Generated by Django 3.1.2 on 2020-10-20 15:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FavMovie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_movie', models.IntegerField(default=0)),
                ('title', models.CharField(max_length=50)),
                ('orginal_title', models.CharField(blank=True, max_length=50, null=True)),
                ('overview', models.TextField(default='None', max_length=800)),
                ('tagline', models.CharField(blank=True, max_length=100, null=True)),
                ('vote_average', models.FloatField(default=0, max_length=35)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('genres', models.CharField(default='None', max_length=35)),
                ('original_language', models.CharField(blank=True, max_length=10, null=True)),
                ('poster_path', models.CharField(blank=True, max_length=100, null=True)),
                ('homepage', models.CharField(blank=True, max_length=100, null=True)),
                ('popularity', models.FloatField(blank=True, max_length=20, null=True)),
                ('note', models.CharField(blank=True, default='this one of my favorite movie', max_length=50, null=True)),
                ('id_user', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'fav_movie',
            },
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('content_type', models.CharField(max_length=70)),
                ('action_flag', models.CharField(max_length=70)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'activity_log',
            },
        ),
    ]
