# Generated by Django 3.1.2 on 2020-10-20 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_auto_20201020_2243'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activitylog',
            old_name='user',
            new_name='username',
        ),
    ]
